name: Deploy
on: ['push']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and build
        run: |
          yarn install
          yarn build
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        if: github.ref == 'refs/heads/master'
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          BRANCH: gh-pages
          FOLDER: build
          SSH: true

